version: '3.8'

services:
  app:
    image: my-spring-boot-app:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge